name: Format

on:
  pull_request:
    branches:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint --fix

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
